version: 2.1
orbs:
  python: circleci/python@2.0.3
jobs:
  build:
    executor: python/default
    steps:
      - checkout  #downloading a copy of the code from the code repository
      - python/install-packages:
          pip-dependency-file: requirements.txt
          pkg-manager: pip
      - persist_to_workspace:
          root: .
          paths:
            - .
  run_test:
    executor: python/default
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run tests
          command: python -m pytest main-test.py
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy: 
    executor: python/default
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Mock deployment
          command: |
            echo "Starting mock deployment..."
            # Add your custom deployment commands here
            echo "Mock deployment completed successfully!"
workflows:
  build_test_deploy:
    jobs:
      - build
      - run_test:
          requires:
            - build
      - deploy:
          requires:
            - run_test
          filters:
              branches:
                only: main #deploy only happens with changes on main