version: 2.1

jobs:
  build:
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout  #downloading a copy of the code from the code repository
      - run:
          name: install req
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
      - persist_to_workspace:
          root: .
          paths:
            - .
  run_test:
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            python -m pytest main-test.py
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy: 
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Mock deployment
          command: |
            echo "Starting mock deployment..."
            # Add your custom deployment commands here
            echo "Mock deployment completed successfully!"
workflows:
  build_test_deploy:
    jobs:
      - build
      - run_test:
          requires:
            - build
      - deploy:
          requires:
            - run_test
          filters:
              branches:
                only: main #deploy only happens with changes on main